export const EXAMENES_CONFIG = [
    {
        column: 1,
        legend: "EXAMEN OCUPACIONAL",
        items: [
            { label: "Triaje", name: "triaje", tabla: "triaje" },
            { label: "Lab. Clínico", name: "labClinico", tabla: "lab_clinico" },
            { label: "Rx. Torax P.A", name: "rxTorax", tabla: "radiografia_torax" },
            { label: "Ficha Audiológica", name: "fichaAudiologica", tabla: "ficha_audiologica" },
            { label: "Audiometría", name: "audiometria", tabla: "audiometria_po" },
            { label: "Espirometría", name: "espirometria", tabla: "funcion_abs" },
            { label: "Odontograma", name: "odontograma", tabla: "odontograma" },
            { label: "Informe Psicológico", name: "psicologia", tabla: "informe_psicologico" },
            { label: "Ficha OIT", name: "fichaOIT", tabla: "oit" },
            { label: "Ex. Rx Sanguíneos", name: "exRxSanguineos", tabla: "ex_radiograficos_sanguineos" },
            { label: "Ficha Ant. Patológicos", name: "fichaAntPatologicos", tabla: "antecedentes_patologicos" },
            { label: "Hist. Ocupacional", name: "histOcupacional", tabla: "historia_oc_info" },
            { label: "Cuestionario Nórdico", name: "cuestionarioNordico", tabla: "cuestionario_nordico" },
            { label: "Ev. Musculo Esquelética", name: "evMusculoEsqueletica", tabla: "evaluacion_musculo_esqueletica" },
            { label: "Oftalmología", name: "oftalmologia", tabla: "oftalmologia" },
            { label: "Actitud Med. Ocupacional", name: "actitudMedOcupacional", tabla: "aptitud_medico_ocupacional_agro" },
            { label: "Uso de Respiradores", name: "usoRespiradores", tabla: "b_uso_respiradores" },
            { label: "Anexo 16-A", name: "anexo16A", tabla: "anexo16a" },
            { label: "Muestra de Sangre", name: "consentimientoDosaje", tabla: "consent_Muestra_Sangre" },
            { label: "Anexo 16", name: "anexo16", tabla: "anexo7c" },
            { label: "Electrocardiograma", name: "electrocardiograma", tabla: "informe_electrocardiograma" },
        ],
    },
    {
        column: 1,
        legend: "Consentimientos",
        items: [
            //{ label: "F. Médica", name: "fMedica" },
            { label: "Const. Informado", name: "ConstInformado", tabla: "consentimientoInformado" },
            { label: "Const. Buena Salud", name: "ConstBuenaSalud", tabla: "consentimientobuenasalud" },
            { label: "Sintomatico Respiratorio", name: "CONSENT_SINTOMATICO", tabla: "CONSENT_SINTOMATICO" },
            { label: "Evaluacion Medica", name: "CONSENT_INFORMADO_MEDICA", tabla: "CONSENT_INFORMADO_MEDICA" },
            { label: "Recepcion Examen Medico", name: "CONSENT_RECOM_MEDIC", tabla: "CONSENT_RECOM_MEDIC" },
            { label: "Declaracion Antecedentes Personales", name: "DECLA_JURA_ANTECE_PERSON_FAM", tabla: "DECLA_JURA_ANTECE_PERSON_FAM" },
            { label: "Declaracion Aptitud Medico O.", name: "DECLA_INFO_APTITUD_MO", tabla: "DECLA_INFO_APTITUD_MO" },
            { label: "Const. Brigadista", name: "ConstBrigadista", tabla: "consta_brigadista" },
            { label: "Conformidad EMO ", name: "ConformidadEmo", tabla: "conformidad_emo" },
        ],
    },
    {
        column: 2,
        legend: "Laboratorio",
        items: [
            { label: "Hemograma", name: "Hemograma", tabla: "hemograma_autom" },
            { label: "Hemoglobina", name: "Hemoglobina", tabla: "lab_clinico_hemoglobina" },
            { label: "Perfil Lipidico", name: "PerfilLipidico", tabla: "analisis_bioquimicos" },
            { label: "Perfil Renal", name: "PerfilRenal", tabla: "l_bioquimica" },
            { label: "Acido Urico", name: "AcidoUrico", tabla: "ac_bioquimica2022" },
            { label: "Perfil Hepatico", name: "PerfilHepatico", tabla: "perfil_hepatico" },
            { label: "Riesgo Coronario", name: "RiesgoCoronario", tabla: "riesgocoronario" },
            { label: "Tolerancia a la Glucosa", name: "ToleranciaGlucosa", tabla: "glucosatolerancia" },
            { label: "Glucosa Basal", name: "GlucosaBasal", tabla: "analisis_bioquimicos_glucosa_basal" },
            { label: "PCR-Ultrasensible", name: "PCRUltrasensible", tabla: "pcr_ultrasensible" },
            { label: "Gonadotropina", name: "Gonadotropina", tabla: "lgonadotropina" },
            { label: "BK - KOH", name: "BKKOH", tabla: "microbiologia" },
            { label: "BK - KOH Directo", name: "BKKOH", tabla: "koh" },
            //
            { label: "Aglutinaciones", name: "Aglutinaciones", tabla: "inmunologia" },
            { label: "Hepatitis", name: "Hepatitis", tabla: "lhepatitis" },
            { label: "VDRL", name: "VDRL", tabla: "inmunologia_vdrl" },
            { label: "VIH", name: "VIH", tabla: "vih" },
            { label: "Thevenon", name: "Thevenon", tabla: "vih" },
            { label: "Toxicologia-Panel 2D", name: "Panel2D", tabla: "panel2d" },
            { label: "Toxicologia-Panel 3D", name: "Panel3D", tabla: "panel3d" },
            { label: "Toxicologia-Panel 4D", name: "Panel4D", tabla: "panel4d" },
            { label: "Toxicologia-Panel 5D", name: "Panel5D", tabla: "toxicologia" },
            { label: "Toxicologia-Panel 10D", name: "Panel10D", tabla: "panel10d" },
            { label: "Etanol saliva", name: "EtanolSaliva", tabla: "etanol_saliva" },
            { label: "Const - Panel 2D", name: "Consentimiento2d", tabla: "con_panel2D" },
            { label: "Const - Panel 3D", name: "Consentimiento3d", tabla: "con_panel3D" },
            { label: "Const - Panel 4D", name: "Consentimiento4d", tabla: "con_panel4D" },
            { label: "Const - Panel 5D", name: "Consentimiento5d", tabla: "con_panel5D" },
            { label: "Const - Panel 10D", name: "Consentimiento10d", tabla: "con_panel10D" },
            { label: "Const - Marihuana", name: "ConsentimientoMari", tabla: "consent_marihuana" },
            { label: "Consentimiento Boro", name: "ConsentimientoBoro", tabla: "consent_boro" },
            { label: "Coprocultivo", name: "Coprocultivo", tabla: "ac_coprocultivo" },
            { label: "Coproparasitológico", name: "Coproparasitológico", tabla: "ac_coproparasitologico" },
            { label: "Examen orina", name: "ExamenOrina", tabla: "lab_clinico_examen_orina" },
            { label: "Prueba Cualitativa Antígenos", name: "PruebaAntigenos", tabla: "examen_inmunologico" },
        ],
    },
    {
        column: 3,
        legend: "Trabajos en Altura",
        items: [
            { label: "Cert. Trab. Altura (Barrik)", name: "certTrabAlturaBarrik", tabla: "b_certificado_altura" },
            { label: "Cert. Trabajo Altura", name: "certTrabajoAltura", tabla: "certificacion_medica_altura" },
        ],
    },
    {
        column: 3,
        legend: "Otros Formatos",
        items: [
            { label: "Ev. Musc. Esquelético", name: "evMuscEsqueletico", tabla: "evaluacion_musculo_esqueletica2021" },
            { label: "Cuest. Calidad Sueño", name: "cuestCalidadSueno", tabla: "calidad_sueño" },
            { label: "Test Fat. Somnolencia", name: "testFatSomnolencia", tabla: "test_fatiga_somnolencia" },
            { label: "Eval. Oftalmológica", name: "evalOftalmologica", tabla: "oftalmologia2021" },
            { label: "Cert. Manipuladores", name: "certManipuladores", tabla: "certificado_manipuladores_barrick" },
            { label: "Cuest. Audiometría", name: "cuestAudiometria", tabla: "cuestionario_audiometria" },
            { label: "Informe Audiometría", name: "informeAudiometria", tabla: "informe_audiometria" },
            { label: "Perímetro Torácico", name: "perimetroToraxico", tabla: "perimetro_toracico" },
        ],
    },
    {
        column: 3,
        legend: "Conducción de Vehículos",
        items: [
            { label: "Ficha S.A.S", name: "fichaSAS", tabla: "ficha_sas" },
            { label: "Cert. Cond. Vehículos (Barrik)", name: "certConduccVehiculos", tabla: "b_certificado_conduccion" },
        ],
    },
    {
        column: 3,
        legend: "Fichas Sin Restricción",
        items: [
            //{ label: "F. Médica", name: "fMedica" },
            { label: "F. Aptitud Med. Ocup.", name: "fAptitudMedOcup", tabla: "certificado_aptitud_medico_ocupacional" },
            { label: "F. Médica Anexo 2", name: "fMedicaAnexo2", tabla: "anexo_agroindustrial" },
            { label: "F. Aptitud Anexo 2", name: "fAptitudAnexo2", tabla: "aptitud_medico_ocupacional_agro" },
        ],
    },
    {
        column: 3,
        legend: "Psicologia",
        items: [
            //{ label: "F. Médica", name: "fMedica" },
            { label: "Informe Fobias", name: "Fobias", tabla: "fobias" },
            { label: "Aversion al Riesgo", name: "AversionRiesgo", tabla: "aversionalriesgo" },
            { label: "Formato Altura Psicologica", name: "AlturaPsico", tabla: "psicologiafobias" },
            { label: "Trastorno Personalidad", name: "TrastornoPersonalidad", tabla: "trastornos_personalidad" },
            { label: "Informe Conductores", name: "InformeConduc", tabla: "infor_conductores" },
            { label: "Alto Riesgo", name: "AltoRiesgo", tabla: "alto_riesgo" },
            { label: "Trabajos Especificos", name: "TrabajosEspeci", tabla: "especificos" },
            { label: "Cuestionario Berlin", name: "CuestionarioBer", tabla: "cuestionario_berlin" },
            { label: "Examen Complementario", name: "ExamComp", tabla: "exam_complementarios" },
            { label: "Brigadista", name: "Brigadista", tabla: "psi_brigadistas" },
            { label: "Bomba Electrico", name: "BombaElec", tabla: "bombaelectrica" },
            { label: "Informe Psicolaboral", name: "InformePsico", tabla: "informe_psicolaboral" },
            { label: "Informe Riesgo Psicosocial", name: "InformeRiesgoPsico", tabla: "informe_riesgos_psicosociales" },
            { label: "Informe Burnout", name: "InformeBurnout", tabla: "informe_burnout" },
            { label: "Informe Psicologico Adeco", name: "InformePsicoAdeco", tabla: "informe_psicologico_estres" },
            { label: "Psicologia Espacios Confinados", name: "PsicoEspaciosConfi", tabla: "psicologia_espacios_confinados" },
        ],
    },

];