export const EXAMENES_CONFIG = [
    {
        column: 1,
        legend: "EXAMEN OCUPACIONAL",
        items: [
            { label: "Triaje", name: "triaje", },
            { label: "Lab. Clínico", name: "labClinico", tabla: "lab_clinico" },
            { label: "Rx. Torax P.A", name: "rxTorax", tabla: "radiografia_torax" },
            { label: "Ficha Audiológica", name: "fichaAudiologica", tabla: "" },
            { label: "Audiometría", name: "audiometria" },
            { label: "Espirometría", name: "espirometria", tabla: "ESPIROMETRIA" },
            { label: "Odontograma", name: "odontograma", tabla: "odontograma" },
            { label: "Informe Psicológico", name: "psicologia" },
            { label: "Ficha OIT", name: "fichaOIT", tabla: "oit" },
            { label: "Ex. Rx Sanguíneos", name: "exRxSanguineos" },
            { label: "Ficha Ant. Patológicos", name: "fichaAntPatologicos", tabla: "antecedentes_patologicos" },
            { label: "Hist. Ocupacional", name: "histOcupacional", tabla: "historia_oc_info" },
            { label: "Cuestionario Nórdico", name: "cuestionarioNordico", tabla: "cuestionario_nordico" },
            { label: "Ev. Musculo Esquelética", name: "evMusculoEsqueletica", tabla: "evaluacion_musculo_esqueletica" },
            { label: "Oftalmología", name: "oftalmologia" },
            { label: "Actitud Med. Ocupacional", name: "actitudMedOcupacional" },
            { label: "Uso de Respiradores", name: "usoRespiradores" },
            { label: "Anexo 16-A", name: "anexo16A" },
            { label: "Consentimiento Dosaje", name: "consentimientoDosaje" },
            { label: "Anexo 16", name: "anexo16" },
            { label: "Electrocardiograma", name: "electrocardiograma" },
        ],
    },
    {
        column: 2,
        legend: "Trabajos en Altura",
        items: [
            { label: "Cert. Trab. Altura (Barrik)", name: "certTrabAlturaBarrik" },
            { label: "Cert. Trabajo Altura", name: "certTrabajoAltura" },
        ],
    },
    {
        column: 2,
        legend: "Otros Formatos",
        items: [
            { label: "Ev. Musc. Esquelético", name: "evMuscEsqueletico" },
            { label: "Cuest. Calidad Sueño", name: "cuestCalidadSueno" },
            { label: "Test Fat. Somnolencia", name: "testFatSomnolencia" },
            { label: "Eval. Oftalmológica", name: "evalOftalmologica" },
            { label: "Cert. Manipuladores", name: "certManipuladores" },
            { label: "Cuest. Audiometría", name: "cuestAudiometria" },
            { label: "Informe Audiometría", name: "informeAudiometria" },
            { label: "Perímetro Torácico", name: "perimetroToraxico" },
        ],
    },
    {
        column: 2,
        legend: "Conducción de Vehículos",
        items: [
            { label: "Ficha S.A.S", name: "fichaSAS" },
            { label: "Cert. Cond. Vehículos (Barrik)", name: "certConduccVehiculos" },
        ],
    },
    {
        column: 3,
        legend: "Fichas Sin Restricción",
        items: [
            { label: "F. Médica", name: "fMedica" },
            { label: "F. Aptitud Med. Ocup.", name: "fAptitudMedOcup" },
            { label: "F. Médica Anexo 2", name: "fMedicaAnexo2" },
            { label: "F. Aptitud Anexo 2", name: "fAptitudAnexo2" },
            { label: "F. Médica Agro", name: "fMedAgro" },
            { label: "F. Aptitud Agro", name: "fAptitudAgro" },
        ],
    },
];