export const EXAMENES_CONFIG = [
    {
        column: 1,
        legend: "EXAMEN OCUPACIONAL",
        items: [
            { label: "Triaje", name: "triaje", tabla: "triaje" },
            { label: "Lab. Clínico", name: "labClinico", tabla: "lab_clinico" },
            { label: "Rx. Torax P.A", name: "rxTorax", tabla: "radiografia_torax" },
            { label: "Ficha Audiológica", name: "fichaAudiologica", tabla: "ficha_audiologica" },
            { label: "Audiometría", name: "audiometria", tabla: "audiometria_po" },
            { label: "Espirometría", name: "espirometria", tabla: "funcion_abs" },
            { label: "Odontograma", name: "odontograma", tabla: "odontograma" },
            { label: "Informe Psicológico", name: "psicologia", tabla: "informe_psicologico" },
            { label: "Ficha OIT", name: "fichaOIT", tabla: "oit" },
            { label: "Ex. Rx Sanguíneos", name: "exRxSanguineos", tabla: "ex_radiograficos_sanguineos" },
            { label: "Ficha Ant. Patológicos", name: "fichaAntPatologicos", tabla: "antecedentes_patologicos" },
            { label: "Hist. Ocupacional", name: "histOcupacional", tabla: "historia_oc_info" },
            { label: "Cuestionario Nórdico", name: "cuestionarioNordico", tabla: "cuestionario_nordico" },
            { label: "Ev. Musculo Esquelética", name: "evMusculoEsqueletica", tabla: "evaluacion_musculo_esqueletica" },
            { label: "Oftalmología", name: "oftalmologia", tabla: "oftalmologia2021" },
            { label: "Actitud Med. Ocupacional", name: "actitudMedOcupacional", tabla: "aptitud_medico_ocupacional_agro" },
            { label: "Uso de Respiradores", name: "usoRespiradores", tabla: "b_uso_respiradores" },
            { label: "Anexo 16-A", name: "anexo16A", tabla: "anexo16a" },
            { label: "Consentimiento Dosaje", name: "consentimientoDosaje", tabla: "consentimiento_dosaje" },
            { label: "Anexo 16", name: "anexo16", tabla: "anexo7c" },
            { label: "Electrocardiograma", name: "electrocardiograma", tabla: "informe_electrocardiograma" },
        ],
    },
    {
        column: 2,
        legend: "Trabajos en Altura",
        items: [
            { label: "Cert. Trab. Altura (Barrik)", name: "certTrabAlturaBarrik", tabla: "b_certificado_altura" },
            { label: "Cert. Trabajo Altura", name: "certTrabajoAltura", tabla: "certificacion_medica_altura" },
        ],
    },
    {
        column: 2,
        legend: "Otros Formatos",
        items: [
            { label: "Ev. Musc. Esquelético", name: "evMuscEsqueletico", tabla: "evaluacion_musculo_esqueletica2021" },
            { label: "Cuest. Calidad Sueño", name: "cuestCalidadSueno", tabla: "calidad_sueño" },
            { label: "Test Fat. Somnolencia", name: "testFatSomnolencia", tabla: "test_fatiga_somnolencia" },
            { label: "Eval. Oftalmológica", name: "evalOftalmologica", tabla: "oftalmologia2021" },
            { label: "Cert. Manipuladores", name: "certManipuladores", tabla: "certificado_manipuladores_barrick" },
            { label: "Cuest. Audiometría", name: "cuestAudiometria", tabla: "cuestionario_audiometria" },
            { label: "Informe Audiometría", name: "informeAudiometria", tabla: "informe_audiometria" },
            { label: "Perímetro Torácico", name: "perimetroToraxico", tabla: "perimetro_toracico" },
        ],
    },
    {
        column: 2,
        legend: "Conducción de Vehículos",
        items: [
            { label: "Ficha S.A.S", name: "fichaSAS", tabla: "ficha_sas" },
            { label: "Cert. Cond. Vehículos (Barrik)", name: "certConduccVehiculos", tabla: "b_certificado_conduccion" },
        ],
    },
    {
        column: 3,
        legend: "Fichas Sin Restricción",
        items: [
            //{ label: "F. Médica", name: "fMedica" },
            { label: "F. Aptitud Med. Ocup.", name: "fAptitudMedOcup", tabla: "certificado_aptitud_medico_ocupacional" },
            { label: "F. Médica Anexo 2", name: "fMedicaAnexo2", tabla: "anexo_agroindustrial" },
            { label: "F. Aptitud Anexo 2", name: "fAptitudAnexo2", tabla: "aptitud_medico_ocupacional_agro" },

        ],
    },
];