export const getAntecedentesDeAlturaInitialFormState = ({
  today,
  userlogued,
  userName,
  userDNI,
  userCMP,
  userEmail,
  userDireccion,
}) => ({
  norden: "",
  codigoAntecedentesAltura: null,
  nombres: "",
  edad: "",
  fechaNacimiento: "",
  lugarNacimiento: "",
  estadoCivil: "",
  nivelEstudios: "",
  fechaExam: today,
  empresa: "",
  contrata: "",
  ocupacion: "",
  cargoDesempenar: "",
  dni: "",
  sexo: "",
  apto: true,

  // Información del médico
  dniMedico: userDNI,
  nombreMedico: userName,
  cmp: userCMP,
  email: (userEmail ?? "").toUpperCase(),
  direccionMedico: (userDireccion ?? "").toUpperCase(),

  // Antecedentes patológicos - todos en false por defecto
  accidenteCerebrovascular: false,
  anginaInestable: false,
  antecedenteBypass: false,
  antecedenteEdemaCerebral: false,
  antecedenteEdemaPulmonar: false,
  antecedenteNeumotorax: false,
  arritmiaCardiaca: false,
  cardiomiopatiaHipertrofica: false,
  cirugiaMayor: false,
  insuficienciaValvulaAortica: false,
  diabetesMellitus: false,
  embarazo: false,
  epilepsia: false,
  epoc: false,
  eritrocitosisExcesiva: false,
  hipertensionArterial: false,
  hipertensionPulmonar: false,
  infartoMiocardio: false,
  insuficienciaCardiaca: false,
  patologiaHemorragicaRetina: false,
  patologiaValvularCardiaca: false,
  presenciaMarcapasos: false,
  riesgoCardiovascularAlto: false,
  trastornosCoagulacion: false,
  trombosisVenosaCerebral: false,
  otros: false,
  otrosDescripcion: "",
  comentarios: "",

  usuario: userlogued ?? "",

  // Médico que Certifica //BUSCADOR
  nombre_medico: userName,
  user_medicoFirma: userlogued,

  // Control de UI: false = mostrar Guardar (nuevo) / true = mostrar Editar (ya existe)
  tieneRegistro: false,

  // Auditoría
  userRegistro: "",
  fechaRegistro: "",
  usuarioActualizacion: "",
  fechaActualizacion: "",
});
